catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('books/', views.BookListView.as_view(), name = 'books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name = 'book-detail'),
    path('authors/', views.AuthorListView.as_view(), name = 'authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name = 'author-detail'),
]

spaceLibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid


class Genre(models.Model):
	name = models.CharField(max_length = 200, help_text = 'Enter a book genre(e.g. Science Fiction)')
	
	def __str__(self):
		return self.name


class Language(models.Model):
	name = models.CharField(max_length = 200, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

	def __str__(self):
		return self.name


class Book(models.Model):
	title = models.CharField(max_length = 200)
	author = models.ForeignKey('Author', on_delete = models.SET_NULL, null = True)
	summary = models.TextField(max_length=1000, null=True, help_text="Enter a brief description of the book")
	isbn = models.CharField('ISBN', max_length = 13, help_text = '13 Character <a href = "https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	genre = models.ManyToManyField(Genre, help_text = 'Select a genre for this book')
	language = models.ForeignKey('Language', on_delete = models.SET_NULL, null = True)

	def display_genre(self):
		return ', '.join([genre.name for genre in self.genre.all()[:3]])

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('catalog:book-detail',args = [str(self.id)])
	
	display_genre.short_description = 'Genre'


class BookInstance(models.Model):
	id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = 'Unique ID for this particular book across whole library')
	book = models.ForeignKey('Book', on_delete = models.SET_NULL, null = True)
	imprint = models.CharField(max_length = 200)
	due_back = models.DateField(null = True, blank = True)

	LOAN_STATUS = (
		('m', 'Maintainance'),
		('o', 'On loan'),
		('a', 'Available'),
		('r', 'Reserved'),
	)

	status = models.CharField(
		max_length = 1,
		choices = LOAN_STATUS,
		blank = True,
		default = 'm',
		help_text = 'Book availability',
	)

	class Meta:
		ordering = ['due_back']

	def __str__(self):
	#	return f'{self.id} ({self.book.title})'
		return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('Died', null=True, blank=True)

	class Meta:
		ordering = ['last_name', 'first_name']
    
	def get_absolute_url(self):
		return reverse('catalog:author-detail', args=[str(self.id)])

	def __str__(self):
		return '{0}, {1}'.format(self.last_name, self.first_name)

catalog/views.py
from django.shortcuts import render
from django.views import generic

from catalog.models import Book, Author, Book, BookInstance, Genre

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()

    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    return render(request, 'index.html', context = context)


class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'

    def get_queryset(self):
        return Book.objects.order_by('title')[:5]
    
    templates_name = 'catalog/book_list.html'
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'author_list'

    def get_queryset(self):
        return Author.objects.order_by('first_name')[:5]
    
    templates_name = 'catalog/author_list.html'
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Local Library</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
       <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    </head>

    <body>

      <!-- Wrapper -->
	      <div id="wrapper">
            
				<!-- Header -->
					<header id="header">
						<span class="avatar"><img src="{% static 'images/avatar.jpg' %}" alt="" /></span>
						<h1>This is my <strong>SpaceLibrary</strong>, a library that gives you a feelings of space. Seriously! I am joking.</h1>
            {% block sidebar %}
						<ul class="icons">
							<li><a href="{% url 'catalog:index' %}" ><span class="label">Home</span></a></li>
							<li><a href="{% url 'catalog:books' %}" ><span class="label">All Books</span></a></li>
							<li><a href="{% url 'catalog:authors' %}" ><span class="label">Author</span></a></li>
							<li><a href="#" ><span class="label">Genre</span></a></li>
							<li><a href="#" ><span class="label">Language</span></a></li>
						</ul>
            {% endblock %}
					</header>
<!--
          
					<section id="main">
						{% block content_post %}
						
							<section class="thumbnails">
								<div>
									<a href="{% static 'images/fulls/01.jpg' %}">
										<img src= "{% static 'images/thumbs/01.jpg' %}"/>
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/02.jpg' %}">
										<img src="{% static 'images/thumbs/02.jpg' %} alt=""/>
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
								</div>
								<div>
									<a href="{% static 'images/fulls/03.jpg' %}">
										<img src="{% static 'images/thumbs/03.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/04.jpg' %}">
										<img src="{% static 'images/thumbs/04.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/05.jpg' %}">
										<img src="{% static 'images/thumbs/05.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
								</div>
								<div>
									<a href="{% static 'images/fulls/06.jpg' %}">
										<img src="{% static 'images/thumbs/06.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/07.jpg' %}">
										<img src="{% static 'images/thumbs/07.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
								</div>
							</section>
						{% endblock %}
					</section>  
-->          
        </div>

      <script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.poptrox.min.js' %}"></script>
			<script src="{% static 'js/skel.min.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>


  <div class="container-fluid">
    <div class="row">
     
      <div class="col-sm-10 ">{% block content %}{% endblock %}
        {% block pagination %}
  {% if is_paginated %}
    <div class="pagination">
      <span class="page-links">
        {% if page_obj.has_previous %}
          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span class="page-current">
          <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
        </span>
        {% if page_obj.has_next %}
          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
      </span>
    </div>
  {% endif %}
{% endblock %} 
      </div>
    </div>
  </div>
</body>

</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author: {{ author }} </h1>
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in book_set.all %}
  <dt><a href="">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
        
        
        
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>
    
  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
 ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %} 
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}

catalog/templates/indexd.html
<!DOCTYPE HTML>
<!--
	Visualize by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Visualize by TEMPLATED</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	</head>
	<body>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<span class="avatar"><img src="{% static 'images/avatar.jpg' %}" alt="" /></span>
						<h1>This is <strong>Visualize</strong>, a responsive site template designed by <a href="http://templated.co">TEMPLATED</a><br />
						and released for free under the Creative Commons License.</h1>
						<ul class="icons">
							<li><a href="{% url 'catalog:index' %}" class="icon style2 fa-twitter"><span class="label">Home</span></a></li>
							<li><a href="{% url 'catalog:books' %}" class="icon style2 fa-facebook"><span class="label">All Books</span></a></li>
							<li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon style2 fa-500px"><span class="label">500px</span></a></li>
							<li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
						</ul>
					</header>

				<!-- Main -->
					<section id="main">

						<!-- Thumbnails -->
							<section class="thumbnails">
								<div>
									<a href="{% static 'images/fulls/01.jpg' %}">
										<img src= "{% static 'images/thumbs/01.jpg' %}"/>
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/02.jpg' %}">
										<img src="{% static 'images/thumbs/02.jpg' %} alt=""/>
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
								</div>
								<div>
									<a href="{% static 'images/fulls/03.jpg' %}">
										<img src="{% static 'images/thumbs/03.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/04.jpg' %}">
										<img src="{% static 'images/thumbs/04.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/05.jpg' %}">
										<img src="{% static 'images/thumbs/05.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
								</div>
								<div>
									<a href="{% static 'images/fulls/06.jpg' %}">
										<img src="{% static 'images/thumbs/06.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
									<a href="{% static 'images/fulls/07.jpg' %}">
										<img src="{% static 'images/thumbs/07.jpg' %}" alt="" />
										<h3>Lorem ipsum dolor sit amet</h3>
									</a>
								</div>
							</section>

					</section>

				<!-- Footer -->
					<footer id="footer">
						<p>&copy; Untitled. All rights reserved. Design: <a href="http://templated.co">TEMPLATED</a>. Demo Images: <a href="http://unsplash.com">Unsplash</a>.</p>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.poptrox.min.js' %}"></script>
			<script src="{% static 'js/skel.min.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>



